[endpoints]
[endpoints.development]
host = "scosta01.aysa.ad"
port = 22
username = "0x00"
private_key = "~/.aysa/0x00_rsa.ppk"
remote_path = "/data/deploy/dashbaord"
force_tag = ""
source_tag = "dev"
target_tag = "rc"

[endpoints.quality]
host = "scosta02.aysa.ad"
port = 22
username = "0x00"
private_key = "~/.aysa/0x00_rsa.ppk"
remote_path = "/data/deploy/dashbaord"
force_tag = "dev"
source_tag = "rc"
target_tag = "latest"

#[endpoints.production]
#host = "scopro01.aysa.ad"
#port = 22
#username = "0x00"
#private_key = "~/.aysa/0x00_rsa.ppk"
#remote_path = "/data/deploy/dashbaord"
#force_tag = ""
#source_tag = "rc"
#target_tag = "latest"

[registry]
host = "sdwsta01.aysa.ad:5000"
insecure = 1
verify = 0
username = "dashboard"
password = "******"
namespace = "dash"
